### ISSUE TITLE
Missing icons?

### ISSUE THREAD

**Issue by gorkamolero** [therufa/mdi-vue#16]
For example color_lens

**Comment by therufa** [comment]
@gorkamolero it might be that the lib is not up-to-date, but in general, it should have most of the icons present on http://materialdesignicons.com/ 
If I understand the issue correctly you're looking for the Palette icon

**Comment by Sendoo** [comment]
Missing icons in 0.2.26+ version.
`import 'mdi-vue/CommentAlertIcon'` - don`t work.
Folder this package in node_modules is almost empty(no icon).

**Comment by therufa** [comment]
@Sendoo Thanks, i have made a mistake with the last publish. it's fixed now.
