### ISSUE TITLE
Export functional components instead

### ISSUE THREAD

**Issue by vintprox** [therufa/mdi-vue#19]
Can we agree on that icons have no reactive state in most situations? So they should be exported as [functional components](https://vuejs.org/v2/guide/render-function.html).
It reduces rendering time a bit.

This change requires:
- all `<template>` tags to be replaced with `<template functional>`,
- add `functional: true` to each non-SFC object representing icon component,
- address all props via corresponding object (e.g. `props.viewBox` instead of sole `viewBox`) in SFC.

Insight on functional components: https://itnext.io/whats-the-deal-with-functional-components-in-vue-js-513a31eb72b0

**Comment by jstgermain** [comment]
It would be very useful to have sizing props that actually worked. In the code, there is width, height, and viewBox.

`export default {
  name: 'mdi-${name}',
  props: {
    width: {
      type: [Number, String],
      default: 24
    },
    height: {
      type: [Number, String],
      default: 24
    },
    viewBox: {
      type: [String],
      default: '0 0 24 24'
    },
    xmlns: {
      type: String,
      default: 'xmlns="http://www.w3.org/2000/svg"'
    }
  }
}`

however, setting these does now work as expected...

`                <map-marker
                    class="text-blue-grey"
                    :width="19"
                    :height="19"
                    :view-box="`0 0 19 19`"
                ></map-marker> {{ mover.city }}, {{ mover.state }}
`

Instead of changing the size, it just cuts off the icon.

**Comment by therufa** [comment]
Hi @vintprox thanks for the recommendation. I'll take a look at what I can do for you regarding this

**Comment by therufa** [comment]
i've just released a new version with functional components. Let's hope I didn't break anything :D
