### ISSUE TITLE
The generated components have a "view-box" attribute, which should be "viewBox"

### ISSUE THREAD

**Issue by robcresswell** [therufa/mdi-vue#2]
As in the title, the attribute added to the generated components appears to be incorrect.

**Comment by robcresswell** [comment]
Specifically, this like is wrong, I think: https://github.com/therufa/mdi-vue/blob/c4e57ad3c7c4c69d3cd59417054969fea8d2a0ee/build.tpl#L4

It should be "viewBox" instead of "view-box". If you load this in a browser and change them, you'll see the icon change size as the viewBox takes effect.

**Comment by therufa** [comment]
Thank you for your time. ill evaluate this and get back to it.

**Comment by robcresswell** [comment]
Thanks so much! You can see more about it here: https://developer.mozilla.org/en/docs/Web/SVG/Attribute/viewBox 

It'd be great to see this fixed, because it makes it very difficult to properly scale these icons otherwise.

**Comment by therufa** [comment]
@robcresswell i believe this is fixed now. i just published the fix a few minutes ago. i hope it will work fine
