### ISSUE TITLE
Support custom classes on icons

### ISSUE THREAD

**Issue by Marivaldi** [therufa/mdi-vue#23]
Since switching the template to be functional, the icon components can no longer accept a custom class on its containing element. Currently the only way to change the color of an icon is to wrap it in another element and give that element the desired CSS color. It would help reduce the number of DOM elements required if you could add a class directly to the span.

`<span :class="['mdi', 'mdi-${name}', data.class, data.staticClass]" :role="props.role" :aria-label="props.ariaLabel">`

**Comment by therufa** [comment]
@Marivaldi thanks for your effort of opening the issue. I'll add this change to the next patch

**Comment by therufa** [comment]
I've released a new patch with the version number v1.2.1
