### ISSUE TITLE
Nuxt.js importing needs .vue extention

### ISSUE THREAD

**Issue by josephfh** [therufa/mdi-vue#26]
Using the latest version of Nuxt.js

`import HookIcon from 'mdi-vue/Hook'`
doesn't work, whereas this does:
`import HookIcon from 'mdi-vue/Hook'.vue`

Could be worth making a note if this is working in normal Vue.js. Thanks!

**Comment by therufa** [comment]
@josephfh thanks for your effort i'll take a look at this when possible. If you have any spare time though, I'm happy to accept guesses or fixes of any sort :D

**Comment by timhoeppner** [comment]
I'm using Nuxt and this isn't an issue for me, I can import without the extension.

**Comment by therufa** [comment]
I don't see this as an issue anymore. We have each file now in the form of a single-file component and compiled to js. Basically you can just import it as stated in the docs, or with the `*.vue` extension
