### ISSUE TITLE
SVG <title> suggestion

### ISSUE THREAD

**Issue by josephfh** [therufa/mdi-vue#27]
The svgs inside each icon's vue components have a title attribute:
`<title>MDI instagram</title>`

I'd like to use these icons inside a link, without the SVG title being used by the browser. I.e.
`<a href="#" title="Inbox"><email-icon /></a>`

Seeing as the icon name is unlikely to be the best wording, it might be better to omit the <title> attribute from the svg altogether.

**Comment by josephfh** [comment]
Pull request for your consideration: https://github.com/therufa/mdi-vue/pull/28

**Comment by therufa** [comment]
Thanks for the input. I merged this by accident though, because the user should have the option to add titles if required. Anyways! Thanks for the changes! They'll be out tomorrow.
