### ISSUE TITLE
Documentation on the component name would be very much appreciated

### ISSUE THREAD

**Issue by robcresswell** [therufa/mdi-vue#3]
It took me a little while to realise that icons with multiple names, like "checkbox-blank-circle-outline", are expected to be input as mdi-checkboxblankcircleoutline-icon. As far as I can see, this isn't really documented anywhere (sorry if I missed it!)

It'd be great to see this documented, to save others time as well.

**Comment by therufa** [comment]
@robcresswell you are absolutely right the behaviour you mentioned is wrong. do you have any suggestions according the documentation?

**Comment by robcresswell** [comment]
I think it would just be good to update the README with an example that includes a multiple word icon, and also a small note underneath that explains the behaviour :)

**Comment by therufa** [comment]
@robcresswell i extended the README. Would you mind to look over it? would be cool

**Comment by robcresswell** [comment]
Looks really good to me. The icons are correctly now rendered as mdi-<kebab-case-name>-icon, and the documentation clearly shows this too. Great work!

**Comment by therufa** [comment]
@robcresswell thank you! Thanks for your contribution too
