### ISSUE TITLE
Any props available?

### ISSUE THREAD

**Issue by A-ZC-Lau** [therufa/mdi-vue#37]
I was wondering if there were any props like `size` or `fillColor` available. This package seems like a more up to date version of [this](https://www.npmjs.com/package/vue-material-design-icons), but without the ability to use props

**Comment by therufa** [comment]
hi @A-ZC-Lau 
right now we don't have `size` and `fillColor` props (although the color is determined by the container's css `color` attribute; meaning you can color icons like you would any text using css).
For size there's `width` and `height` as props but if you have something more specific in mind, please let me know

**Comment by A-ZC-Lau** [comment]
That's cool, maybe you could make a small update to the documentation to note these capabilities?
