### ISSUE TITLE
any props to make the loader spinning?

### ISSUE THREAD

**Issue by rheddi02** [therufa/mdi-vue#38]
as the title says, or maybe I just don't know what to put to make it spinning. Thank you

**Comment by therufa** [comment]
hi @rheddi02,
I'm not sure if i can follow you on this. which icon do you mean by this. 
Also, please keep in mind, that this library only provides svg icons. 

Maybe you're looking for something like these spinners https://github.com/Saeris/vue-spinners?

cheers!

**Comment by NomNes** [comment]
@therufa I think @rheddi02 means the "spin" property for adding animation to any icon (like FA icons)

**Comment by therufa** [comment]
@NomNes thanks, that's actually a great idea for a feature. i'll give it some thought

**Comment by therufa** [comment]
@rheddi02 so, if what you meant with this was what @NomNes is suggesting, then v1.5.0 should be having this feature.
Just add the `spin` property to the desired icon, and it will make it spin around.
The spin property is a boolean value, which defaults to false.

```
<CogIcon spin />
```
or:
```
<CogIcon :spin="true" />
```

I hope this does the job. Thanks to you both!
