### ISSUE TITLE
Icon not found

### ISSUE THREAD

**Issue by SimonFricker** [therufa/mdi-vue#39]
This dependency was not found: ClipboardEditOutline.vue 

`import ClipboardEditOutlineIcon from 'mdi-vue/ClipboardEditOutline.vue'`

MDI Icon link https://materialdesignicons.com/icon/clipboard-edit-outline

**Comment by therufa** [comment]
Hi Simon, thanks for reporting this issue. I see this [icon was added to material design icons](https://github.com/Templarian/MaterialDesign/issues/5214#issuecomment-640090537) after the last update of this lib. 
Should be up-to-date in a few minutes :)

**Comment by therufa** [comment]
It's been deployed, you can update now. Thanks for your patience :)

**Comment by SimonFricker** [comment]
@therufa thanks for the reply. 

I updated the package `"mdi-vue": "^1.6.3",` however Vue still fails to compile because it can not find the icon `mdi-vue/ClipboardEditOutline.vue`

**Comment by therufa** [comment]
@SimonFricker I'm afraid my hands are tied on this; like many other similar libraries this one uses [Templarian/MaterialDesign-JS](https://github.com/Templarian/MaterialDesign-JS) to generate all the icons. 
After a little investigation, I have noticed that it's out of date. To speed up the process I'll open an issue over there.

(Take a look for yourself, `ClipboardEdit` is missing completely 
https://github.com/Templarian/MaterialDesign-JS/blob/master/mdi.js)

Once we have an update I'll publish a new package. Thanks again!

**Comment by therufa** [comment]
Just pushed a release with some new icons @SimonFricker. I hope still in time 😅
