### ISSUE TITLE
Major version should be incremented when @mdi/js major version changes

### ISSUE THREAD

**Issue by EqualMa** [therufa/mdi-vue#42]
When I update `mdi-vue` from [`1.4.3`](https://github.com/therufa/mdi-vue/tree/v1.4.3) to [`https://github.com/therufa/mdi-vue/tree/v1.6.4`], my build breaks because of the `GithubBox` icon is no longer available.

Then I look into the `@mdi/js` versions, I found it upgrades from [`4.7.95`](https://cdn.materialdesignicons.com/4.7.95/) to [`5.4.55`](https://cdn.materialdesignicons.com/5.4.55/), so some icons are no longer available.

I think the version of mdi-vue should also increment the major version when the major version of `@mdi/js` changes.

**Comment by therufa** [comment]
hi @EqualMa,  
thanks for your remarks I didn't think of this, but you're right. I'll take this into account next time I make a dependency update. 
In case you have any recommendations for a system or anything, please don't hesitate to add your thoughts.

**Comment by therufa** [comment]
Since i've changed how the lib behaves, this became irrelevant.
