### ISSUE TITLE
Can't style icons with :class attribute

### ISSUE THREAD

**Issue by robertfausk** [therufa/mdi-vue#43]
I'm unable to style an icon by passing a :class to the component.

```vue
<template>
  <div>
    <circle-icon 
      :class="{'active': true}" 
    />
  </div>
</template>
```

The resulting `<span>` will not include "active".

This seems to be related to #30

**Comment by TomerPacific** [comment]
@therufa , I'd like to help (if it is still needed). Some guidance will be appreciated.

**Comment by therufa** [comment]
hi @TomerPacific , thanks for the interest in the project. 
The issue is rather small, so I believe that something like `:class="data.staticClass || ''"` is missing on the component template next to where attributes are bound to the component.

**Comment by TomerPacific** [comment]
@therufa , thanks for that clarification.
I have made the change and have opened a PR.
