### ISSUE TITLE
Support for Vue 3

### ISSUE THREAD

**Issue by layanto** [therufa/mdi-vue#44]
Does this work with Vue 3? I think Vue 3 has removed support for functional template/component.

**Comment by therufa** [comment]
Thanks for bringing this up! It seems it does break with vue 3 therefore it should be moved to plain components or something else. Sadly I have limited time during the upcoming weeks, so this might take a little longer to implement.

**Comment by HunterJS-bit** [comment]
@therufa 
The template.js has to be converted to support Vue 3 syntax, in Vue 3 `functional` attribute is removed from template
Here is a guide how: https://v3.vuejs.org/guide/migration/functional-components.html#_3-x-syntax
I could try to work on this if you want ?
