### ISSUE TITLE
vue 3 can not make kebab-case named icons work

### ISSUE THREAD

**Issue by Zony-Zhao** [therufa/mdi-vue#48]
I managed to use`<mdicon name="account" />` , but failed at both `<mdicon name="format-text" />` and `<mdicon name="format-Text" />`

**Comment by therufa** [comment]
Hi @Zony-Zhao, thanks for pointing this out. Even though this is not a bug it's very inconvenient.
You see, in https://github.com/Templarian/MaterialDesign-JS/blob/master/mdi.js the names are camelCase therefore the name prop should be camel case as well, meaning that `<mdicon name="formatText" />` should work. (See  https://github.com/therufa/mdi-vue/blob/master/main.js#L19)

I'll add a patch soon which will allow to use the component more intuitively, until then I'd suggest to simply go for camel or pascal case.

Thanks again

**Comment by therufa** [comment]
@Zony-Zhao I released an upgrade, now it should work now with the format you've tried initially.
