### ISSUE TITLE
Add possibility to use object for property "class"

### ISSUE THREAD

**Issue by robertfausk** [therufa/mdi-vue#54]
It would be nice if the following is working:
 ```VUE
<mdicon
  v-if="isOpen"
  name="ArrowCollapseVertical"
  :class="{ 'text-blue': isOpen, 'text-red': !isOpen }"
/>
```
but it is just simply ignored.

Currently i depend on following workaround:
```VUE
<mdicon
  v-if="isOpen"
  name="ArrowCollapseVertical"
  class="text-blue"
/>
<mdicon
  v-else
  name="ArrowCollapseVertical"
  class="text-red"
/>

**Comment by therufa** [comment]
Hi @robertfausk, thanks for reporting this issue. Could you please provide a little more detail on which version of vue you've been using?

**Comment by robertfausk** [comment]
> Hi @robertfausk, thanks for reporting this issue. Could you please provide a little more detail on which version of vue you've been using?

Of course :)
I am using ```"mdi-vue": "2.2.0"``` and ```"vue": "2.6.12"```.
Same for #52 and #53

**Comment by therufa** [comment]
@robertfausk i've just released a fix for this with v2.2.3 on npm. 

Feedback is highly appreciated. Keep up the good work! :)

**Comment by ataylor32** [comment]
I'm getting this warning in v2.2.3, but not v2.2.2:

```
[Vue warn]: Property "class" was accessed during render but is not defined on instance.
at <MDIcon name="alert" >
at <App>
```

**Comment by larescze** [comment]
> I'm getting this warning in v2.2.3, but not v2.2.2:
> 
> ```
> [Vue warn]: Property "class" was accessed during render but is not defined on instance.
> at <MDIcon name="alert" >
> at <App>
> ```

Same problem with vue ^3.0.5.

**Comment by therufa** [comment]
hey @larescze and @ataylor32,
I've updated the lib to a new major version due to a few breaking changes, but the warnings should be gone now. The import path changed though, so you'd need to import the lib as follows: `import mdiVue from 'mdi-vue/v2'`

**Comment by larescze** [comment]
> hey @larescze and @ataylor32,
> I've updated the lib to a new major version due to a few breaking changes, but the warnings should be gone now. The import path changed though, so you'd need to import the lib as follows: `import mdiVue from 'mdi-vue/v2'`

I just checked it out and the warnings no longer appear. Great work!

**Comment by therufa** [comment]
> > hey @larescze and @ataylor32,
> > I've updated the lib to a new major version due to a few breaking changes, but the warnings should be gone now. The import path changed though, so you'd need to import the lib as follows: `import mdiVue from 'mdi-vue/v2'`
> 
> I just checked it out and the warnings no longer appear. Great work!

Thanks! :) closing this issue then
