### ISSUE TITLE
Won't work with runtime only build of vue

### ISSUE THREAD

**Issue by Dor-Ron** [therufa/mdi-vue#6]
Since icons are .js and not .vue files

**Comment by therufa** [comment]
Thanks for the remark, i'm going to look into this issue ASAP.

**Comment by logiclabs** [comment]
Any news on this?  I've just attempted to use the library but instead of the icons it's rendering:
```
<!--function (a, b, c, d) { return createElement(vm, a, b, c, d, true); }-->
```
I think the templates need pre-compiling before packaging i.e. https://vuejs.org/v2/guide/deployment.html#Pre-Compiling-Templates

**Comment by linusg** [comment]
Still having the same problem...

**Comment by linusg** [comment]
I used https://gitlab.com/robcresswell/vue-material-design-icons as a perfectly working alternative.

**Comment by leep0o** [comment]
https://github.com/Justineo/vue-awesome

**Comment by linusg** [comment]
@leep0o do you realize this project is about **Material Design Icons**? The link you've posted states (emphasis mine):

> Awesome SVG icon component for Vue.js, with built-in **Font Awesome icons**.

**Comment by leep0o** [comment]
> @leep0o do you realize this project is about **Material Design Icons**? The link you've posted states (emphasis mine):
> 
> > Awesome SVG icon component for Vue.js, with built-in **Font Awesome icons**.

I suggested an alternative!

**Comment by alejandroiglesias** [comment]
After a year this is still happening. Cannot use it.

**Comment by therufa** [comment]
I updated the package recently, and now this issue should be obsolete. Please reopen if it's still the case
