### ISSUE TITLE
vue3+typescript cannot be used

### ISSUE THREAD

**Issue by zatsunen** [therufa/mdi-vue#61]
main.ts prompt: "MDI: Icon mdi-vue not found" 

main.js :
import mdiVue from 'mdi-vue/types/v3'
import * as mdiJs from '@mdi/js'

createApp(app)
  .use(mdiVue, { icons: mdiJs })

build output:
This dependency was not found:

* mdi-vue/types/v3 in ./src/main.ts

To install it, you can run: npm install --save mdi-vue/types/v3

**Comment by larescze** [comment]
Or you can declare the module in the **shims-vue.d.ts** file or other .d.ts file.

```declare module 'mdi-vue/v3'```

Example **shims-vue.d.ts**:
```
declare module '*.vue' {
  import { DefineComponent } from 'vue'
  const component: DefineComponent<{}, {}, any>
  export default component
}
declare module 'mdi-vue/v3'
declare module 'vuedraggable/src/vuedraggable'
declare module 'vue3-markdown-it'
```

**Comment by zatsunen** [comment]
> Or you can declare the module in the **shims-vue.d.ts** file or other .d.ts file.
> 
> `declare module 'mdi-vue/v3'`
> 
> Example **shims-vue.d.ts**:
> 
> ```
> declare module '*.vue' {
>   import { DefineComponent } from 'vue'
>   const component: DefineComponent<{}, {}, any>
>   export default component
> }
> declare module 'mdi-vue/v3'
> declare module 'vuedraggable/src/vuedraggable'
> declare module 'vue3-markdown-it'
> ```

Excellent,thank you so much
