### ISSUE TITLE
Error Nuxt in SSR mode

### ISSUE THREAD

**Issue by Sendoo** [therufa/mdi-vue#64]
### Versions

- nuxt: v2.15.6
- node: v14.17.3 LTS

### Problem
Hi✌

If you run the plugin with the following code: 

```
import Vue from 'vue';
import mdiVue from 'mdi-vue/v2'
import * as mdijs from '@mdi/js'

Vue.use(mdiVue, {
  icons: mdijs
}) 
```

Then we get this error:

![изображение](https://user-images.githubusercontent.com/46229254/125172991-612bcf00-e1c5-11eb-9f9b-0b01d45dc911.png)

If you run the plugin in client mode, then there is no error.
But there is a big delay in displaying icons.

**Comment by Sendoo** [comment]
It seems that it turned out to run 🙂
When using Nuxt.js, `mdi-vue` should be added to the transpile build option in nuxt.config.js:

```
export default {
  // ...
  build: {
    transpile: ['mdi-vue']
  }
}
```

Maybe you should add this to your plugin documentation?

**Comment by therufa** [comment]
Thanks for the addition @Sendoo, fair point :)
