### ISSUE TITLE
Tree shaking icons using Vite

### ISSUE THREAD

**Issue by adarshmadrecha** [therufa/mdi-vue#65]
Since we are using the 
`import * as mdijs from '@mdi/js'` in below initialization, all the icons are imported.
Is it possible to enable tree shaking so that only the icons which are used are bundled?

```js
import { createApp } from 'vue'
import mdiVue from 'mdi-vue/v3'
import * as mdijs from '@mdi/js'

createApp(App).use(mdiVue, {
  icons: mdijs
}) // etc...
```

**Comment by therufa** [comment]
hi @adarshmadrecha, the feature you're mentioning is already a feature of most build tools available, so to utilize this you just need to import the desired icons by name.

```
import {
	mdiSpaceStation,
	mdiApplication,
	mdiExclamation
} from '@mdi/js'

createApp(App).use(mdiVue, {
 	icons: {
		  mdiSpaceStation,
		  mdiApplication,
		  mdiExclamation
	}
})
```

It might seem a bit redundant, but it's the cleanest solution I know of. Once the icons are imported, you can use them as in the examples. 

OFF: Also, here's a handy tool for searching icons: https://therufa.github.io/mdi-search/

I hope that I could help you a bit. 
Cheers

**Comment by adarshmadrecha** [comment]
Actually, I was looking for something like Vuetify, Element Plus. They import fully, but at Build time the tree shaking removes components which are not Used.

**Comment by therufa** [comment]
Thanks for the hint, your input is much appreciated

**Comment by Zony-Zhao** [comment]
This is not tree shaking though...
My code:
![image](https://user-images.githubusercontent.com/50739849/145933585-0346bcf0-c1c7-4838-83c1-30b5eb1c2ca2.png)
My build with webpack --report:
![image](https://user-images.githubusercontent.com/50739849/145933645-d69ef65b-925e-4439-9833-ca629050b801.png)


> hi @adarshmadrecha, the feature you're mentioning is already a feature of most build tools available, so to utilize this you just need to import the desired icons by name.
> 
> ```js
> import {
> 	mdiSpaceStation,
> 	mdiApplication,
> 	mdiExclamation
> } from '@mdi/js'
> 
> createApp(App).use(mdiVue, {
>  	icons: {
> 		  mdiSpaceStation,
> 		  mdiApplication,
> 		  mdiExclamation
> 	}
> })
> ```
> 
> It might seem a bit redundant, but it's the cleanest solution I know of. Once the icons are imported, you can use them as in the examples.
> 
> OFF: Also, here's a handy tool for searching icons: https://therufa.github.io/mdi-search/
> 
> I hope that I could help you a bit. Cheers
