### ISSUE TITLE
Throws warnings for width/height props with units

### ISSUE THREAD

**Issue by DDeBruler** [therufa/mdi-vue#7]
Both the [width](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width#svg) and [height](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/height#svg) attributes of `<svg>` elements can properly be specified as [length](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#Length) or [percentage](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#Percentage) content types.  The generated components pass any specified values along to the rendered SVG, which then displays at the appropriate size, but if the specified values include units (e.g. `1em`, `12px`, etc.), the component logs a warning to the console:
```
[Vue warn]: Invalid prop: type check failed for prop "height". Expected Number, got String.
```

**Comment by therufa** [comment]
This should be fixed with the new release. Thanks for your efforts!
